`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Module Name: full_subtractor.sv
// Description: 1-bit full subtractor built from two half subtractors and an OR gate.
//   Stage 1: HS1 subtracts b from a, gives: diff1, bout1
//   Stage 2: HS2 subtracts bin from diff1, gives: diff(final), bout2
//   bout(final) = bout1 OR bout2  (borrow generated by either stage)
//////////////////////////////////////////////////////////////////////////////////
module full_subtractor (
    input  logic a,     // minuend
    input  logic b,     // subtrahend
    input  logic bin,   // borrow-in
    output logic diff,  // difference
    output logic bout   // borrow-out
);

    logic diff1, bout1, bout2;

    // Stage 1: a - b
    half_subtractor hs1 (.a(a), .b(b), .diff(diff1), .bout(bout1));

    // Stage 2: diff1 - bin
    half_subtractor hs2 (.a(diff1), .b(bin), .diff(diff), .bout(bout2));

    // Final borrow-out: set if either stage needed to borrow
    assign bout = bout1 | bout2;

endmodule
